version: "3.7"
services:
  polipo:
    image: currycan/ssrpolipo:1.0.0
    container_name: polipo
    restart: always
    network_mode: "host"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
    # sysctls:
    #   net.core.rmem_max: 26214400
    #   net.core.rmem_default: 26214400
    #   net.core.wmem_max: 26214400
    #   net.core.wmem_default: 26214400
    #   net.core.netdev_max_backlog: 10000
    #   net.ipv6.conf.all.disable_ipv6: 1
    #   net.ipv6.conf.default.disable_ipv6: 1
    #   net.ipv6.conf.lo.disable_ipv6: 1
    #   net.ipv4.neigh.default.gc_stale_time: 120
    #   net.ipv4.conf.all.rp_filter: 0
    #   net.ipv4.conf.default.rp_filter: 0
    #   net.ipv4.conf.default.arp_announce: 2
    #   net.ipv4.conf.lo.arp_announce: 0
    #   net.ipv4.conf.all.arp_announce: 0
    #   net.ipv4.tcp_fastopen: 3
    #   kernel.shmall: 268435456
    #   net.ipv4.ip_forward: 1
    #   net.ipv4.tcp_mem: 786432 1048576 1572864
    #   net.ipv4.tcp_retries2: 5
    #   net.ipv4.tcp_keepalive_time: 600
    #   net.ipv4.tcp_keepalive_intvl: 30
    #   net.ipv4.tcp_keepalive_probes: 10
    #   net.ipv4.conf.lo.arp_ignore: 0
    #   net.ipv4.conf.all.arp_ignore: 0
    #   net.ipv4.conf.default.accept_source_route: 0
    #   kernel.msgmnb: 655360
    #   kernel.msgmax: 655360
    #   kernel.shmmax: 68719476736
    #   net.ipv4.tcp_orphan_retries: 3
    #   net.ipv4.tcp_reordering: 5
    #   net.ipv4.tcp_retrans_collapse: 0
    #   net.ipv4.tcp_sack: 1
    #   net.ipv4.tcp_window_scaling: 1
    #   net.core.default_qdisc: fq
    #   net.ipv4.tcp_max_tw_buckets: 5000
    #   net.ipv4.tcp_syncookies: 1
    #   net.ipv4.tcp_max_syn_backlog: 1024
    #   net.ipv4.tcp_synack_retries: 2
    #   net.bridge.bridge-nf-call-ip6tables: 1
    #   net.bridge.bridge-nf-call-iptables: 1
    #   net.bridge.bridge-nf-call-arptables: 1
    #   net.ipv4.neigh.default.gc_thresh1: 1024
    #   net.ipv4.neigh.default.gc_thresh2: 4096
    #   net.ipv4.neigh.default.gc_thresh3: 8192
    #   net.netfilter.nf_conntrack_max: 10485760
    #   net.netfilter.nf_conntrack_tcp_timeout_established: 300
    #   net.netfilter.nf_conntrack_buckets: 655360
