map $ssl_preread_server_name $tcpsni_name  {
    reality.${DOMAIN}                   vlessr;     # 用户站
    trojan.${DOMAIN}                    trojan;     # Trojan 的域名
    ${CDNDOMAIN}                        cdnh2;      # HTTP/2 server 的域名
    ${DOMAIN}                           http3;      # HTTP/3 server 的域名
}

upstream vlessr {
    server                              unix:/dev/shm/udsreality.sock; #转给 VLESS+Vision+TLS 本地监听端口
}

upstream trojan {
    server                              unix:/dev/shm/udstrojangrpc.sock; #转给 Trojan 监听进程
}

upstream cdnh2 {
    server                              unix:/dev/shm/cdnh2.sock; #转给 HTTP/2 server 监听进程
}

upstream http3 {
    server                              unix:/dev/shm/web.sock; #转给 HTTP/3 server 监听进程
}

server {
    listen ${LISTENING_PORT} reuseport;
    listen [::]:${LISTENING_PORT} reuseport ipv6only=on; #无 IPv6，此项可删除。
    ssl_preread on;
    proxy_protocol on; #启用 PROXY protocol 发送。（全局模式）
    proxy_pass $tcpsni_name ;
}
