map $ssl_preread_server_name $tcpsni_name  {
    # 主域名/CDN域名 -> 转发给 Nginx 内部 SSL 端口 (cdnh2)
    ${DOMAIN}                           cdnh2;
    ${CDNDOMAIN}                        cdnh2;

    # 伪装域名 -> 转发给 Xray Reality 端口 (vlessr)
    ${DEST_HOST}                        vlessr;
}

upstream vlessr {
    server                              unix:/dev/shm/udsreality.sock; #转给 VLESS+Vision+TLS 本地监听端口
}

upstream cdnh2 {
    server                              unix:/dev/shm/cdnh2.sock; #转给 HTTP/2 server 监听进程
}

server {
    listen ${LISTENING_PORT} reuseport;
    listen [::]:${LISTENING_PORT} reuseport ipv6only=on; #无 IPv6，此项可删除。
    ssl_preread on;
    proxy_protocol on; #启用 PROXY protocol 发送。（全局模式）
    proxy_pass $tcpsni_name ;
}
