version: "3"
services:
  v2ray:
    image: currycan/v2ray-web:1.0.3
    container_name: v2ray
    environment:
      - DOMAIN=$domain
      - ALTERID=0
      - LISTENING_PORT=443
    volumes:
      - ./pki:/pki
      - ./acme:/acme.sh
      - ./config/v2ray:/etc/v2ray
      - ./config/nginx:/etc/nginx/conf.d
      - ./logs/v2ray:/var/log/v2ray
      - ./logs/nginx:/var/log/nginx
    # working_dir: /etc/nginx
    restart: always
    network_mode: "host"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
