services:
  file:
    image: currycan/ng-file:1.0.0
    container_name: file
    volumes:
    - ./data:/var/www/file
    restart: always
    network_mode: "host"

  sub-store:
    image: xream/sub-store
    container_name: substore
    restart: always
    environment:
    - SUB_STORE_CRON=55 23 * * *
    # http://127.0.0.1:3010/sDFye2FvHNJwheeCkXQpGaGRQBtupYGS
    - SUB_STORE_FRONTEND_BACKEND_PATH=/sDFye2FvHNJwheeCkXQpGaGRQBtupYGS
    ports:
    - "3010:3001"
    volumes:
    - ./substore:/opt/app/data
