version: "3.7"
services:
  ssrkcp:
    image: currycan/ssrkcp:1.0.0
    container_name: ssrkcp
    # restart: always
    network_mode: "host"
    cap_add:
       - NET_ADMIN
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      net.core.somaxconn: 16384
      net.ipv4.tcp_syncookies: 1

  # polipo:
  #   image: currycan/polipo:1.0.0
  #   container_name: polipo
  #   ports:
  #     - "18080:18080"
  #   restart: always
  #   ulimits:
  #     nproc: 65535
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   sysctls:
  #     net.core.somaxconn: 16384
  #     net.ipv4.tcp_syncookies: 1
