version: "3"
services:
  xray:
    image: currycan/xray-web:1.0.0
    container_name: xray
    environment:
      - DOMAIN=$domain
    volumes:
      - ./config/xray:/etc/xray
      - ./logs/xray:/var/log/xray
    restart: always
    network_mode: "host"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
